EVENT_DICT = {
    # Messen ---------------------------------------
    "Heilige Messe":"Heilige Messe",
    "Eucharistiefeier":"Heilige Messe",
    "EUF": "Heilige Messe",
    "MF": "Heilige Messe",
    "VAM": "Heilige Messe",
    "Hochamt": "Heilige Messe",
    "HOCHAMT": "Heilige Messe",
    "Hl. Amt": "Heilige Messe",
    "Dankgottesdienst": "Heilige Messe",
    "Vorabendmesse": "Heilige Messe",
    "Messfeier": "Heilige Messe",
    "Hl. Messe": "Heilige Messe",
    "Eucharistie": "Heilige Messe",
    "Pilgermesse": "Heilige Messe",
    "Frühmesse": "Heilige Messe",
    "Abendmesse": "Heilige Messe",
    "Frauenmesse": "Heilige Messe",
    "Frauen- und Müttermesse":  "Heilige Messe",
    "Familienmesse":"Heilige Messe",
    "Familiengottesdienst": "Heilige Messe",
    "Festliches Hochamt": "Heilige Messe",
    "Festgottesdienst": "Heilige Messe",
    # Ostern ----------------------------------------
    "Osternachtfeier": "Heilige Messe",  
    "Osternachtsfeier": "Heilige Messe",
    "Osternachtliturgie": "Heilige Messe",
    "Osternachtsliturgie": "Heilige Messe",
    "Osternachtmesse": "Heilige Messe",
    "Auferstehungsfeier": "Heilige Messe",
    "Ostermesse": "Heilige Messe",
    "Feier der Osternacht": "Heilige Messe",
    "Osternacht": "Heilige Messe",
    # Weiteres ----------------------------------------
    "Andacht": "Andacht",
    "Beichte": "Beichte",
    "Beichtgelegenheit": "Beichte",
    "Trauerfeier": "Beerdigung",
    "Beerdigung": "Beerdigung",
    "Requiem": "Beerdigung",
    "Bussgottesdienst": "Bussgottesdienst",
    "Erstkommunion": "Erstkommunion",
    "Firmung": "Firmung",
    "Hochzeit": "Hochzeit",
    "Trauung": "Hochzeit",
    "Rosenkranzgebet": "Rosenkranz",
    "Taufsonntag": "Taufe",
    "Taufe": "Taufe",
    "Tauffeier": "Taufe",
    "Rosenkranz": "Rosenkranz",
    "Wortgottesfeier": "Wortgottesdienst",
    "Wort-Gottes- und Kommunion-Feier": "Wortgottesdienst",
    "Wortgottesdienst": "Wortgottesdienst",
    "Wort-Gottes-Feier": "Wortgottesdienst",
    "Kindergottesdienst": "Kindergottesdienst",
    "Kinderkirche": "Kindergottesdienst",
    "Chile für Chind": "Kindergottesdienst",
    "KLEINKINDER-FEIER": "Kindergottesdienst",
    # Messen generisch -----------------------------------
    "Fiire mit de Chliine": "Kindergottesdienst",
    "Magyar Mise": "Heilige Messe",
    "Santa Messa": "Heilige Messe",
    "Misa": "Heilige Messe",
    "Messe": "Heilige Messe",
    "Gottesdienst": "Heilige Messe", # Must be places last 
    # to avoid Problems with Wortgottesdienst
}

LANGUAGES = {
    "(ungarisch)": "Ungarisch",
    "Ungarischer Gottesdienst": "Ungarisch",
    "Magyar": "Ungarisch",
    "portugiesischer Sprache": "Portugiesisch",
    "in Portugiesisch": "Portugiesisch",
    "Tamilischer": "Tamilisch",
    "Englische": "Englisch",
    "in lingua italiana": "Italienisch",
    "en español": "Spanisch",
    "in kroatischer Sprache": "Kroatisch",
    "in polnischer Spracne": "Polnisch",
    "Eritreer": "Altäthiopisch",
    "Slowenischer": "Slowenisch",
    "Slowenische": "Slowenisch",
    "Indische": "Tamilisch",
}